### ISSUE TITLE
overabundance npm package

### ISSUE THREAD

**Issue by HawkeyePierce89** [natewatson999/node-virustotal#11]
Are you sure that all these files are necessary? Maybe you should clean the unnecessary? https://docs.npmjs.com/files/package.json.html#files

![image](https://user-images.githubusercontent.com/25603805/76082164-c6f9bc80-5fbb-11ea-89ce-8db65070a742.png)

**Comment by natewatson999** [comment]
To answer your question, yes. Each one is required.

The JS files above LICENSE are all for legacy compatibility which was assured in Version 3.0.0 and above; as are oldReadme.md, repl.js, tester.js, and that trio between the README.md file and the package.json.

v3.js and v3Test.js are both current versions. obvious_virus.svg is for testing. Everything else is more meta like documentation and package info.
