### ISSUE TITLE
Can't use v3 version

### ISSUE THREAD

**Issue by BrunoMarley289** [natewatson999/node-virustotal#13]
When I install the package it installs version 3.19 but when I put a "." in front of the constant nvt he gives me other options, here's a print: https://imgur.com/s3yhgMc 
and when I execute the code this gives an error: 

> (node:6168) UnhandledPromiseRejectionWarning: TypeError: nvt.makeAPI is not a function

**Comment by ludovicoloreti** [comment]
up

**Comment by natewatson999** [comment]
Sorry for the delay. I'm investigating the issue.

**Comment by natewatson999** [comment]
I think I found the problem. Something went wrong with the package file. It's pointing to the wrong file. I'm fixing it right now.

**Comment by natewatson999** [comment]
This has been fixed as of 3.22.0 . Thank you for bringing this issue to me.
