### ISSUE TITLE
Implementing Promises

### ISSUE THREAD

**Issue by Yuvaleros** [natewatson999/node-virustotal#2]
Is it possible to implement promises in the library?
When trying to promisify the library functions using bluebird, fatal errors occur, such as:
`TypeError: errProc is not a function`

Thanks!

**Comment by natewatson999** [comment]
I've never actually checked to see if promises are implementable.

However, if a bug is being encountered, it should be investigated.

Are you using the public, honeypot, private, intelligence, or email API? Are you using the CLI? Which method is giving this issue? Can you show me the code you are using to use said method?

**Comment by Yuvaleros** [comment]
I'm using the private API on a node server.

The code I'm using : 
```
const Promise = require('bluebird');

let con = vt.makePrivateConnection();
con.setKey("XXXXXXXX");
let getIP4Report= Promise.promisify(con.getIP4Report);

getIP4Report("X.X.X.X")
    .then((res) => {
        console.log(res);
    })
    .catch((err) => {
        //It seems that the virustotal client returns the data in the error argument when it's promisified.
        console.log(err);
    })
```

To reproduce the fatal error you need to cause an error in the library function, try putting a bad argument in the "getIP4Report" function, something like: "1.1.1".

After promisifiying the getIP4Report function, the results are returned in the "catch" function instead of the "then" function (this happens in any case even if there is no error).
It's beside the point but worth mentioning.

**Comment by natewatson999** [comment]
Fair warning: you're probably going to encounter a lot of this stuff. The private API isn't well tested. I don't have a private Key to test with, so a lot of this is running blind. I have asked Virustotal for one, but haven't gotten a response.

That being said, I'm investigating.

**Comment by natewatson999** [comment]
I've checked using bluebird and the public API. The same problems you describe happen. 

From what I can tell, Bluebird isn't designed to handle the way this API is supposed to be used. If you'd like, we could file a bug with the publisher of Bluebird. Alternatively, if you'd like, I could try to implement something with an interface that's as close as possible.

**Comment by Yuvaleros** [comment]
Can you elaborate about implementing an interface that is close as possible?

When saying that Bluebird isn't designed to handle the way the Virus-Total is supposed to be used - Are you referring to the fact that the Virus-Total API uses both success and failure callbacks?

**Comment by natewatson999** [comment]
What I mean was that I would try to add a feature to convert between this API's dual-callback system and Bluebird's single-callback format, and then let people layer Bluebird into it.

Yes, it is because of the dual-callback system. Bluebird appears to only be designed for singular ones.

**Comment by Yuvaleros** [comment]
Sounds like a good idea 👍

**Comment by natewatson999** [comment]
Go to the documentation. Just above the Security And Legal Notes, there's a section called "formatConverter". This is for a new feature I've added. This function won't convert a function with callbacks to a promise, but it will convert a function into a function that bluebird.js can use. I hope this meets your requirements. Please confirm if it works for you.

**Comment by Yuvaleros** [comment]
Thank you very much! the "formatConverter" is a good solution and it works, but out of curiosity, why not create a function/interface that gets the error or the result and resends them in a single callback function?

**Comment by natewatson999** [comment]
I originally wrote the API without any consideration for promises. 

Outside of promises, usually the code to handle the errors is completely different from the code to handle actual results. So I saw no logical reason for them to be the same function, since they're probably going to be doing very different things. In a weird way, the way promises are used there confirms that, since they treat them as separate functions as well. Bottom line, it was for simplicity of code.

I'm glad it works for you. Let me know if you encounter any other issues, particularly with the private API.
