### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by DanielRuf** [natewatson999/node-virustotal#3]
I guess it would be helpful to setup CI and some unit tests.

**Comment by natewatson999** [comment]
Yeah that would be helpful. 

Can you suggest a test tool you think would be best for this particular project?

**Comment by DanielRuf** [comment]
I think Jest could be useful.

**Comment by natewatson999** [comment]
Would you be interested in making some of it for this project?

**Comment by DanielRuf** [comment]
If I find the time, sure.
